theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"
color-modes = true
cursorline = true
end-of-line-diagnostics = "disable"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true # Show LSP status (initializing, etc)

[editor.indent-guides]
render = true
character = "╎"
skip-level = 1

[editor.inline-diagnostics]
prefix-len = 1
max-diagnostics = 10
cursor-line = "warning" # show warnings and errors on the cursorline inline
other-lines = "disable"
min-diagnostic-width = 40

[keys.normal]
A-h = ":toggle file-picker.hidden"

[keys.normal.space.d]
d = "diagnostics_picker"
i = ":toggle inline-diagnostics.cursor-line warning hint"
