# BEGIN_KITTY_THEME
# Gruvbox Dark Hard
include current-theme.conf
# END_KITTY_THEME

# BEGIN_KITTY_FONT
font_family      Hack Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
# END_KITTY_FONT

# BEGIN_TAB_BAR
tab_bar_style powerline
# END_TAB_BAR

# BEGIN_LAYOUTS
enabled_layouts splits,tall,horizontal
# END_LAYOUTS

# BEGIN_WINDOWS
window_margin_width 5
single_window_margin_width 0
window_padding_width 5
single_window_padding_width 10

active_border_color #689d6a
inactive_border_color #928374
# END_WINDOWS

map f5 launch --location=hsplit
map f6 launch --location=vsplit
map shift+up move_window up
map shift+left move_window left
map shift+right move_window right
map shift+down move_window down
